import { Inter } from 'next/font/google'
import './globals.css'
import Nabvar from '@/components/shared/Nabvar'
import Footer from '@/components/shared/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'The Dragon News',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='max-w-screen-xl mx-auto'>
          <Nabvar></Nabvar>
          <div className='min-h-screen'>
            {children}
          </div>
          <Footer></Footer>
        </div>
      </body>
    </html>
  )
}
