import { Inter } from 'next/font/google'
import './globals.css'
import Nabvar from '@/components/shared/Nabvar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'The Dragon News',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nabvar></Nabvar>
        {children}
      </body>
    </html>
  )
}
